### PR TITLE
docs: add markers for badges paragraph

### PR DESCRIPTION
**Pull request by maelle**
# Prework

* [x] I understand and agree to the [R-releases Code of Conduct](https://r-releases.github.io/conduct.html).
* [ ] I have already submitted a [discussion topic](https://github.com/r-releases/releases/discussions) or [issue](https://github.com/r-releases/releases/issues) to discuss my idea with the maintainer.

# Related GitHub issues and pull requests

* Ref: #

# Summary

Please explain the purpose and scope of your contribution.

### CODE REVIEW

**Comment by llrs** [comment]
Is this needed for `usethis::use_badge` or is it used by some other tools that add badges?

**Comment by wlandau** [comment]
Looking at the source code of `usethis::use_badge()`, as well as non-exported objects like `usethis:::block_append()`, `usethis:::badge_start`, and `usethis:::badge_end`, it appears these comments do help `usethis` insert badges automatically. Thanks for catching this, @maelle.

**Review by wlandau — APPROVED** [review]

**Comment by maelle** [comment]
sorry for the lack of context! this also helps pkgdown detects the badges, now they're in the sidebar: https://r-releases.github.io/releases/

**Comment by llrs** [comment]
Thanks I wasn't sure why was needed, @maelle!

**Pull request merged**
